name: Build & Deploy phuc.wtf

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: jphuc96/phuc.wtf

jobs:

  build-docker:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$GITHUB_SHA --tag ${{ env.IMAGE_NAME }}:latest --no-cache
    - name: Login to docker.io
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Image
      run: docker push ${{ env.IMAGE_NAME }}:$GITHUB_SHA
  
  deploy-kubernetes:
    name: deploy to cluster
    needs: [build-docker]
    runs-on: ubuntu-latest
    steps:
    - uses: danielr1996/kubectl-action@1.0.0
      name: Deploy
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        args: set -n phucwtf image --record deployment/phucwtf phucwtf=${{ env.IMAGE_NAME }}:$GITHUB_SHA
    - uses: danielr1996/kubectl-action@1.0.0
      name: Rollout
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        args: rollout -n phucwtf status deployment/phucwtf