name: Build & Deploy phuc.wtf

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-docker:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag reg.phuc.wtf/phuc.wtf:$GITHUB_SHA
    - name: Push Image
      run: docker push reg.phuc.wtf/phuc.wtf:$GITHUB_SHA
  
  deploy-kubernetes:
    name: deploy to cluster
    needs: [build-docker]
    runs-on: ubuntu-latest
    steps:
    - uses: danielr1996/kubectl-action@1.0.0
      name: Deploy
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        args: set -n phucwtf image --record deployment/phucwtf phucwtf=reg.phuc.wtf/phuc.wtf:$GITHUB_SHA
    - uses: danielr1996/kubectl-action@1.0.0
      name: Rollout
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        args: rollout -n phucwtf status deployment/phucwtf
  
#     - uses: actions/checkout@master
#     - name: deploy to cluster
#       uses: steebchen/kubectl@master
#       env:
#         KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#       with:
#         args: set -n phucwtf image --record deployment/phucwtf phucwtf=reg.phuc.wtf/phuc.wtf:$GITHUB_SHA
#     - name: verify deployment
#       uses: steebchen/kubectl@master
#       env:
#         KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#         KUBECTL_VERSION: "1.17"
#       with:
#         args: '"rollout -n phucwtf status deployment/phucwtf"'
