name: Build and Push Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag reg.phuc.wtf/phuc.wtf:$GITHUB_SHA
    - name: Push Image
      run: docker push reg.phuc.wtf/phuc.wtf:$GITHUB_SHA
